name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          memory_limit: 256M
      - uses: php-actions/phpunit@v3
        with:
          test_suffix: Test.php
      - uses: php-actions/phpstan@v3
